---
settings:
  name: Astra Automation 21.12
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '21.12'
    url: "/astra-automation-2112"
  - version-number: '23.10'
    url: "/astra-automation"
  - version-number: '23.07'
    url: "/astra-automation-2307"
  - version-number: '23.04'
    url: "/astra-automation-2304"
  - version-number: '22.11'
    url: "/astra-automation-2211"
  - version-number: '22.08'
    url: "/astra-automation-2208"
  - version-number: '22.04'
    url: "/astra-automation-2204"
  - version-number: '21.08'
    url: "/astra-automation-2108"
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Astra Control Automation 21.12文件
    url: "/index.html"
  - section: rn
  - section: intro
  - section: get-started
  - section: rest-core
  - section: additional
  - section: endpoints
  - section: workflows_infra
  - section: workflows
  - section: python
  - section: reference
  - section: information
  - title: 舊版
    url: "/aa-earlier-versions.html"
  - title: 法律聲明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 開始使用
    links:
    - title: 簡介
      summary: 取得Astra REST API的總覽。
      url: "/intro/introduction.html"
    - title: 開始之前
      summary: 準備開始使用REST API。
      url: "/get-started/before_get_started.html"
    - title: 取得API權杖
      summary: 產生存取API所需的權杖。
      url: "/get-started/get_api_token.html"
    - title: 您好：World
      summary: 測試REST API的基本存取。
      url: "/get-started/hello_world.html"
  - title: REST實作
    links:
    - title: REST Web服務
      summary: 瞭解REST Web服務的技術基礎。
      url: "/rest-core/rest_web_services.html"
    - title: HTTP詳細資料
      summary: 檢閱HTTP實作的詳細資料。
      url: "/rest-core/http_details.html"
    - title: URL格式
      summary: 瞭解URL格式、以及它如何由多個值組成。
      url: "/rest-core/url_format.html"
  - title: 其他考量
    links:
    - title: 安全性
      summary: 探索REST API所提供的安全性。
      url: "/additional/security.html"
    - title: 使用集合
      summary: 使用查詢參數存取資源集合。
      url: "/additional/working_with_collections.html"
    - title: 診斷與支援
      summary: 準備支援Astra應用程式。
      url: "/additional/diagnostics_support.html"
  - title: 資源
    links:
    - title: 資源與收藏
      summary: 熟悉REST資源和集合的設計。
      url: "/rest-core/resources_collections.html"
    - title: Astra Control REST API資源
      summary: 檢閱各種Astra資源的簡明簡介。
      url: "/endpoints/resources.html"
  - title: 工作流程
    links:
    - title: 準備
      summary: 準備好使用Astra工作流程。
      url: "/get-started/prepare_to_use_workflows.html"
    - title: 基礎架構工作流程
      summary: 維護Astra執行時間基礎架構所需的工作流程。
      url: "/workflows_infra/workflows_infra_before.html"
    - title: 管理工作流程
      summary: 用於管理託管應用程式的一般工作流程。
      url: "/workflows/workflows_before.html"
  - title: Python
    links:
    - title: 開始之前
      summary: 準備執行範例Python指令碼。
      url: "/python/python_before.html"
    - title: 列出託管應用程式
      summary: 執行範例指令碼以列出託管應用程式。
      url: "/python/py_list_man_apps.html"
product-family:
  name: Astra
  repo: astra-family
